server:
  port:
spring:
  application:
    name: stock
  datasource:
    username: root
    password: q1234321
    url: jdbc:mysql://localhost:3306/instock?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver